language: php
php:
  - 7.1
  - 7.2
  - 7.3
install:
- composer self-update --no-interaction
- composer update --no-interaction --prefer-dist
env:
- XDEBUG_MODE=coverage
script:
- composer test
- composer cs
